### ISSUE TITLE
new feature: add scroll animations to the website

### ISSUE THREAD

**Issue by m-code12** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#66]
We can add scroll animations to the website especially on the home page to keep our users engaged with our content. Animations will be used to focus users attention on what's important and will also show the flow of our website.

**Comment by s-ayush2903** [comment]
Would you like to take up this issue?

**Comment by m-code12** [comment]
> Would you like to take up this issue?

Yes.

**Comment by s-ayush2903** [comment]
Go ahead then!

**Comment by m-code12** [comment]
Please assign me points for opening this issue.

**Comment by s-ayush2903** [comment]
Done

**Comment by s-ayush2903** [comment]
@m-code12 You'll be un-assigned if not opened PR for the issue, to make this issue open for others to work on.

**Comment by m-code12** [comment]
Sorry, I was having my exams hence I couldn't make one. I will make a pr soon.

**Comment by m-code12** [comment]
@s-ayush2903 I have raised a pr #68, check it out.
