### ISSUE TITLE
Stats Icons in register page are less semantic

### ISSUE THREAD

**Issue by s-ayush2903** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#74]
**Describe the problem**
Icons present in the register page of the website are very less semantic when it comes to the text written below them.

**Proposed fix/solution**
Those icons need to be changed in accordance to the entity mentioned there.

**Screenshots/Visuals**
![icons](https://user-images.githubusercontent.com/56556919/102699318-b4f6bb00-4269-11eb-86e2-de72c267fb41.png)

**Comment by yash0501** [comment]
@s-ayush2903 I would like to work on this issue. Please assign it to me.

**Comment by yash0501** [comment]
Is this ok?
If yes, I will make a PR for it.
![pr](https://user-images.githubusercontent.com/60708843/103153061-a6515c00-47b3-11eb-98aa-e49051d177f0.jpg)

**Comment by s-ayush2903** [comment]
@yash0501 It'll be better if for projects we use the icon that github uses for repositories, like the one which you can see adjacent to a repository's name, this'll be nice. And I believe the icon for participants too can be changed. You may look for icons on [undraw.co](https://undraw.co/illustrations), it is a nice place for tasks like this.

**Comment by yash0501** [comment]
![new](https://user-images.githubusercontent.com/60708843/103167493-7ce70d80-4851-11eb-919f-e99b0a311529.jpg)
Is it OK now?

**Comment by s-ayush2903** [comment]
We don't need three dots/mini-squares on the projects icon, and for participants icon, we can revert back to the very first version that you suggested, after these changes, it'll be fine.

**Comment by s-ayush2903** [comment]
Closing in favor of #80
