### ISSUE TITLE
unable to view the leaderboard 

### ISSUE THREAD

**Issue by tusharnankani** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#82]
It has been like this for quite some hours.

![image](https://user-images.githubusercontent.com/61280281/103173976-66a67500-4884-11eb-9866-90e88df7b1dc.png)

**Comment by s-ayush2903** [comment]
We are aware of it, it is being diagnosed where the problem crept in as we had all clean merges none went bad or below quality

**Comment by s-ayush2903** [comment]
See #83
