### ISSUE TITLE
Add contributors list in the readme

### ISSUE THREAD

**Issue by m-code12** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#87]
We can add the list of contributors who contributed to this repository similar to this :

![Screenshot (294)](https://user-images.githubusercontent.com/53649201/103304639-2cc5a200-4a2f-11eb-8a6f-24270d66128c.png)

Or maybe something like [hall of fame](https://github.com/sourcerer-io/hall-of-fame/blob/develop/README.md) .

I would like to implement this.

**Comment by m-code12** [comment]
I would like to work on this

**Comment by m-code12** [comment]
@s-ayush2903 Should I go ahead and implement this?

**Comment by s-ayush2903** [comment]
We don't need it, as all the contributors can be seen from _[contributors](https://github.com/NJACKWinterOfCode/NJACKWinterOfCode.github.io/graphs/contributors)_ section of the repository.

**Comment by m-code12** [comment]
Yeah, that's there. I'll be making use of the same link to display the contributors. 
We can have the contributors list easily accessible in the readme as most of the repositories have, anyways, it's your call.

**Comment by m-code12** [comment]
> We don't need it, as all the contributors can be seen from _[contributors](https://github.com/NJACKWinterOfCode/NJACKWinterOfCode.github.io/graphs/contributors)_ section of the repository.

Yeah, that's there. I'll be making use of the same link to display the contributors.
We can have the contributors list easily accessible in the readme as most of the repositories have, anyways, it's your call.

**Comment by s-ayush2903** [comment]
The aim of a readme file is to provide new devs an idea of what the project is about and how to work on developing and some context/motto of the project, even now that file looks quite off-topic to me, we'll clean it up as the program finishes so we don't need more stuff that isn't coherent with the aim of the file, and therefore we don't need the requested change here.
