### ISSUE TITLE
Add a scroll-to-top button on the website

### ISSUE THREAD

**Issue by m-code12** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#88]
I would like to add a new feature to the website, a scroll-to-top button that will take the user to the top of the page when clicked on. This comes quite handy when the user reaches the end of the page and has to scroll way back to the top.

**Comment by m-code12** [comment]
Should I go ahead and implement this? @s-ayush2903

**Comment by s-ayush2903** [comment]
Yep this is necessary, I was too lazy to create a ticket for it, so thanks for creating it. Yes you may work on it
