### ISSUE TITLE
add search bar for selection of projects

### ISSUE THREAD

**Issue by Vishal-raj-1** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#91]
**Is your feature request related to a problem? Please describe.**
A search bar in project page will help participants to select project on the basis of their tech stack. 

**Describe the solution you'd like**
I will add a search bar at the top of projects. which will show projects on the basis of search terms.

**Comment by s-ayush2903** [comment]
@Vishal-raj-1 Let us know if you wish to work on this issue

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 Let us know if you wish to work on this issue

yes
