### ISSUE TITLE
showing icons instead of links

### ISSUE THREAD

**Issue by Vishal-raj-1** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#92]
**Is your feature request related to a problem? Please describe.**
Clicking on links is not looks nice to me on contact page.

**Describe the solution you'd like**
 I would like to suggest have icons for facebook , twitter , github , gitter and mails.

![contact](https://user-images.githubusercontent.com/59874304/103509724-c951cf00-4e89-11eb-8032-9ea437433370.JPG)

**Comment by nishihere19** [comment]
**Home-page**
-Buttons: Share on Facebook, Share on twitter.
-Removing the underline from the "Follow us on facebook, twitter, etc below timeline.
-Follow on social media links in the footer at the bottom of the page.
**Projects Page**
-Mentor links (Can add their profile images from github as links)
**Contact Us Page**
-Social Media Links
-Names of members can be directly linked to Facebook links.

Did you mean the points mentioned above? Can I work on the issue?

**Comment by s-ayush2903** [comment]
@nishihere19 Have you planned the new UI after the removal of these texts and links, as after making these changes the page would look so blank(and maybe weird), have you thought of any compensation for that?

**Comment by nishihere19** [comment]
Icons will be added everywhere except in the last suggestion. I mean to directly link the name of the person with their id on contact us page.

**Comment by Vishal-raj-1** [comment]
@nishihere19 Hey I have solve only contact Page issue(which is opened by me) !! You can solve other issues mentioned by you.
