### ISSUE TITLE
footer design for 404 error page

### ISSUE THREAD

**Issue by Vishal-raj-1** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#94]
**Describe the bug**
style of footer is not consistent 

**To Reproduce**
adding styling like other page footer

# Now
![footer](https://user-images.githubusercontent.com/59874304/103533839-db486780-4eb3-11eb-841d-c1b33770e525.JPG)

# will do like this
![foo](https://user-images.githubusercontent.com/59874304/103534021-206c9980-4eb4-11eb-8b56-93fe6dd0f46f.JPG)

**Comment by nishihere19** [comment]
Can you assign this to me? I can resolve it.

**Comment by Vishal-raj-1** [comment]
You can go for it !! 🙃 @nishihere19

**Comment by nishihere19** [comment]
Thanks
