### ISSUE TITLE
footer is not responsive

### ISSUE THREAD

**Issue by Vishal-raj-1** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#98]
**Describe the bug**
The content of footer is overflow.

**To Reproduce**
1. can use media query OR border box property.

**Expected behavior**
It should not be overflowed.

**Screenshots**
![footerbug](https://user-images.githubusercontent.com/59874304/103619911-8f9bc980-4f58-11eb-9027-65165770c844.JPG)

**Comment by Vishal-raj-1** [comment]
@nishihere19 do you want to work on this issue ?

**Comment by nishihere19** [comment]
Nope, I am not sure if I can handle media query.

**Comment by Vishal-raj-1** [comment]
> Nope, I am not sure if I can handle media query.

sure !! @s-ayush2903  Please assign this issue to me !!

**Comment by NikhilSharmaWe** [comment]
looking forward to solve this issue

**Comment by satcasm** [comment]
Is it still available?

**Comment by s-ayush2903** [comment]
No, we already have a mergeable PR
