### ISSUE TITLE
Archive Page using summary and details tag

### ISSUE THREAD

**Issue by Vishal-raj-1** [NJACKWinterOfCode/NJACKWinterOfCode.github.io#99]
**Is your feature request related to a problem? Please describe.**
Currently there is lot of scrolling on the archive page.

**Describe the solution you'd like**
What we can do is hide the projects until user search for specific year's project.

## Video

https://user-images.githubusercontent.com/59874304/103624612-c7f2d600-4f5f-11eb-8edc-3a46491c8ca3.mp4

**Additional context**
There is two things that I can do(if needed):
1. can show Previous Sponsors( means will remove summary tag)
2. further styling suggested by you !!

@s-ayush2903 @Ankit7Das do you like this ? if you like this so I can make a quick PR for this !!

**Comment by s-ayush2903** [comment]
I like the proposal, but it'll look more better if we can see a flow when a text is clicked, very similar to the one which we see when on codeforces, in the editorial of a contestst we click on `Solution` and a dropdown occurs, that looks really nice, we can do that

**Comment by Vishal-raj-1** [comment]
> I like the proposal, but it'll look more better if we can see a flow when a text is clicked, very similar to the one which we see when on codeforces, in the editorial of a contestst we click on `Solution` and a dropdown occurs, that looks really nice, we can do that

Sir could you please send the video on screenshots !!

**Comment by s-ayush2903** [comment]
Give a look to [this editorial](https://codeforces.com/blog/entry/86126), you would be able to understand
